[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cryptography>=44.0.1",
    "fastapi==0.99.0",
    "pymysql>=1.1.1",
    "sqlalchemy>=2.0.38",
    "uvicorn>=0.34.0",
]
